# Generated by Django 4.1 on 2022-08-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game_name',
        ),
    ]
